spring:
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false
  h2:
    console:
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /api

security:
  jwt:
    token:
      secret-key: mm-secret
      expire-length: 600000 #10 minutes duration by default: 10 min * 60 sec * 1000 mls

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
  refresh: Return a new Token
